# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import github_fetcher.api.services.github_fetcher_pb2 as github__fetcher__pb2


class GithubFetcherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_info = channel.unary_unary(
                '/stats.fetcher.grpc.GithubFetcher/get_info',
                request_serializer=github__fetcher__pb2.GithubFetcherRequest.SerializeToString,
                response_deserializer=github__fetcher__pb2.GithubFetcherResponse.FromString,
                )


class GithubFetcherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GithubFetcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_info,
                    request_deserializer=github__fetcher__pb2.GithubFetcherRequest.FromString,
                    response_serializer=github__fetcher__pb2.GithubFetcherResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stats.fetcher.grpc.GithubFetcher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GithubFetcher(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stats.fetcher.grpc.GithubFetcher/get_info',
            github__fetcher__pb2.GithubFetcherRequest.SerializeToString,
            github__fetcher__pb2.GithubFetcherResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
